---
title: "BayesianAnalysis"
output: html_document
---

```{r}
library(tidyverse)
library(faraway)
library(caret)
```

```{r BAC_calculator}
#standard formula 
shots <- readline(prompt = "Enter number of shots: ")
a = 0.6 * as.numeric(shots)
r = 0.68
w = 120
h = 2

bac = ((a * 5.14) / (w * r)) - (0.015 * h)
bac
```

```{r BAC_calculator2}
#change beta and r
#r can be modeled as a function of weight gender height age and water drank
shots <- readline(prompt = "Enter number of shots: ")
weight <- readline(prompt = "Enter weight: ")
height <- readline(prompt = "Enter height (in): ")
age <- readline(prompt = "Enter age: ")
a = 0.6 * as.numeric(shots)
r = 0.68
h = 2
beta = 0.015

#formula for men
r_update_men = (2.447 - 0.09156 * as.numeric(age) + 0.1074 * as.numeric(height) * 2.54 + 0.3362 * (as.numeric(weight) * 0.45359237)) / (as.numeric(weight) * 0.45359237)

#formula for women
r_update_women = (-2.097 + 0.1069 * as.numeric(height) * 2.54 + 0.2466 * (as.numeric(weight) * 0.45359237)) / (as.numeric(weight) * 0.45359237)

bac_update = ((a * 5.14) / (as.numeric(weight) * r_update_men)) - (beta * h)
bac_update
```

```{r CSV}
waterInfo <- read.csv("waterdata.csv")
waterInfo$percent <- waterInfo$watervol / waterInfo$weight
waterInfo
```

```{r}
IndependenceC <- aov(percent ~ gender, data = waterInfo)
summary.aov(IndependenceC)

waterInfoM <- waterInfo[waterInfo$gender == 1,]
quantile(waterInfoM$bodyfat_percent)[[2]]

for (i in 1:length(waterInfoM$bodyfat_percent)){
  if(waterInfoM$bodyfat_percent[i] <= quantile(waterInfoM$bodyfat_percent)[[2]]){
    waterInfoM$fat[i] <- "low"
  } else if(waterInfoM$bodyfat_percent[i] <= quantile(waterInfoM$bodyfat_percent)[[4]]){
    waterInfoM$fat[i] <- "mid"
  } else {
    waterInfoM$fat[i] <- "high"
  }
}
waterInfoM[,c(8, 10)]

model_M <- lm(percent ~ age + weight + height, data = waterInfoM)
summary(model_M)

waterInfoF <- waterInfo[waterInfo$gender == 2,]
quantile(waterInfoF$bodyfat_percent)

model_F <- lm(percent ~ age + weight + height, data = waterInfoF)
summary(model_F)
```

```{r}

test <- data.frame(age = c(19),
                   weight = c(50),
                   height = c(164)
                   
)
r_update_men <- predict(model_M, test)
print (paste("Updated R:", r_update_men))

shots <- readline(prompt = "Enter number of shots: ")
weight <- readline(prompt = "Enter weight: ")
height <- readline(prompt = "Enter height (in): ")
age <- readline(prompt = "Enter age: ")
a = 0.6 * as.numeric(shots)
beta = 0.015

bac_update = ((a * 5.14) / (as.numeric(weight) * r_update_men)) - (beta * h)
bac_update
```

```{r}

plot(waterInfo$percent ~ waterInfo$weight)
plot(waterInfo[waterInfo$gender == 2,]$percent ~ waterInfo[waterInfo$gender == 2,]$weight)
plot(waterInfo[waterInfo$gender == 1,]$percent ~ waterInfo[waterInfo$gender == 1,]$weight)

plot(waterInfo$percent ~ waterInfo$height)
plot(waterInfo[waterInfo$gender == 2,]$percent ~ waterInfo[waterInfo$gender == 2,]$height)
plot(waterInfo[waterInfo$gender == 1,]$percent ~ waterInfo[waterInfo$gender == 1,]$height)
```

```{r}
IndependenceC <- aov(percent ~ gender, data = waterInfo)
summary.aov(IndependenceC)


model_M1 <- lm(percent ~ age + weight + height, data = waterInfoM)
summary(model_M1)


model_M2 <- lm(percent ~ age + weight + height + fat, data = waterInfoM)
summary(model_M2)
plot(model_M2$residuals ~ model_M1$fitted.values)
qqnorm(model_M2$residuals)
```
```{r}
test <- data.frame(age = c(19, 19, 20),
                   weight = c(54.5, 54.5, 70),
                   height = c(165, 165, 175.26),
                   fat = c("low", "mid", "low")
                   
)
r_update_men <- predict(model_M2, test)
print (paste("Updated R:", r_update_men))
```

```{r}
testnormal <- data.frame(sample = rnorm(10, mean = 0.02, sd = 0.0025)
)

library(tidyverse)
library(brms)
library(rstan)
install.packages("rstanarm")
library(rstanarm)
library(tidybayes)
library(ggdist)
library(posterior)
```

```{r}
testnormal <- data.frame(sample = rnorm(2, mean = 0.025, sd = 0.025)
)
testnormal
fit <- stan_glm(sample ~ 1, data = testnormal, family = gaussian(),
                prior = normal(0.015, 0.0025), cores = 4, seed = 1)
```
```{r}
posterior_interval(fit, prob = 0.95)
coef(fit)
```

